pipeline {
  agent {
    docker {
      image 'docker:26.1.0-cli'
      args '-u root -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  environment {
    IMAGE_NAME   = "mgopi1982/python-demo-app"
    DOCKER_CONFIG = "${WORKSPACE}/.docker"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "${IMAGE_NAME}:${BUILD_NUMBER}"
        REGISTRY_CREDENTIALS = credentials('docker-cred')
      }
      steps {
        script {
          sh '''
            mkdir -p ${DOCKER_CONFIG}
            docker build -t ${DOCKER_IMAGE} .
          '''

          def dockerImage = docker.image("${DOCKER_IMAGE}")
          docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
            dockerImage.push()
          }
        }
      }
    }
  }

  post {
    cleanup {
      sh 'docker logout || true'
    }
  }
}
