pipeline {
  agent {
    docker {
      image 'docker:26.1.0-cli'
      args '-v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  environment {
    IMAGE_NAME = "mgopi1982/python-demo-app"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "${IMAGE_NAME}:${BUILD_NUMBER}"
        REGISTRY_CREDENTIALS = credentials('docker-cred')
      }
      steps {
        script {
          // Build Docker image
          sh '''
            docker build -t ${DOCKER_IMAGE} .
          '''

          // Push Docker image to Docker Hub
          def dockerImage = docker.image("${DOCKER_IMAGE}")
          docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
            dockerImage.push()
          }
        }
      }
    }
  }

  post {
    success {
      echo "Docker image successfully pushed: ${IMAGE_NAME}:${BUILD_NUMBER}"
    }
    cleanup {
      sh 'docker logout || true'
    }
  }
}
